# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SimpleExample add-on
version: "1.2.1"
slug: example
description: SimpleExample add-on
url: "https://github.com/jubr/hassio-addons/tree/main/example"
arch:
  #- armhf
  - armv7
  #- aarch64
  #- amd64
  #- i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/jubr/{arch}-addon-example"
